<a href="https://colab.research.google.com/github/neerajmahajan83/resumeNeerajM/blob/main/pythontutorial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [15]:
import pandas as pd

data = {
    'Product': ['Laptop', 'Mouse', 'Monitor'],
    'Price': [1200, 25, 300],
    'In_Stock': [True, True, False]
}

df = pd.DataFrame(data)

data1 = [
    ['Alice', 25, 'Engineer'],
    ['Bob', 30, 'Designer'],
    ['Charlie', 22, 'Intern']
]

df1 = pd.DataFrame(data1, columns=['Name', 'Age', 'Role'])

df2 = pd.concat([df, df1], ignore_index=True)

# Fix the ValueError by adding suffixes for overlapping columns
# Also, fix the typo 'prin' to 'print'
df3 = df2.join(df1, lsuffix='_df2', rsuffix='_df1')

print(df3)

   Product   Price In_Stock Name_df2  Age_df2  Role_df2 Name_df1  Age_df1  \
0   Laptop  1200.0     True      NaN      NaN       NaN    Alice     25.0
1    Mouse    25.0     True      NaN      NaN       NaN      Bob     30.0
2  Monitor   300.0    False      NaN      NaN       NaN  Charlie     22.0
3      NaN     NaN      NaN    Alice     25.0  Engineer      NaN      NaN
4      NaN     NaN      NaN      Bob     30.0  Designer      NaN      NaN
5      NaN     NaN      NaN  Charlie     22.0    Intern      NaN      NaN

   Role_df1
0  Engineer
1  Designer
2    Intern
3       NaN
4       NaN
5       NaN

In [16]:
import pandas as pd

# 1. Create your dictionary object
student_grades = {
    "Alice": 92,
    "Bob": 85,
    "Charlie": 78,
    "Diana": 95
}

# 2. Convert it into a pandas Series
series = pd.Series(student_grades)

print(series)

Alice      92
Bob        85
Charlie    78
Diana      95
dtype: int64

To identify missing values, we'll use the `.isnull()` method, which returns a boolean DataFrame indicating `True` for missing values and `False` otherwise. We can then combine this with `.sum()` to count them.

In [17]:
import pandas as pd
import numpy as np

# Create a sample DataFrame with some missing values
df_sample = pd.DataFrame({
    'A': [1, 2, np.nan, 4, 5],
    'B': [np.nan, 7, 8, 9, 10],
    'C': ['apple', 'banana', 'orange', np.nan, 'grape'],
    'D': [True, False, True, False, np.nan]
})

print("Original DataFrame:")
display(df_sample)

# 1. Check for missing values in each column
print("\nMissing values per column:")
display(df_sample.isnull().sum())

# 2. Total number of missing values in the entire DataFrame
print("\nTotal missing values in the DataFrame:")
display(df_sample.isnull().sum().sum())

# 3. Identify rows with any missing values
print("\nRows with any missing values:")
display(df_sample[df_sample.isnull().any(axis=1)])

# 4. Check for missing values in the entire DataFrame (returns boolean if any exists)
print("\nAre there any missing values in the DataFrame?")
display(df_sample.isnull().any().any())

Original DataFrame:

     A     B       C      D
0  1.0   NaN   apple   True
1  2.0   7.0  banana  False
2  NaN   8.0  orange   True
3  4.0   9.0     NaN  False
4  5.0  10.0   grape    NaN

Missing values per column:

A    1
B    1
C    1
D    1
dtype: int64

Total missing values in the DataFrame:

np.int64(4)

Rows with any missing values:

     A     B       C      D
0  1.0   NaN   apple   True
2  NaN   8.0  orange   True
3  4.0   9.0     NaN  False
4  5.0  10.0   grape    NaN

Are there any missing values in the DataFrame?

np.True_

In [19]:
# Fill null values with 'test'
df_filled = df_sample.fillna('test')

print("DataFrame after filling null values with 'test':")
display(df_filled)

print("\nMissing values after filling:")
display(df_filled.isnull().sum())

DataFrame after filling null values with 'test':

      A     B       C      D
0   1.0  test   apple   True
1   2.0   7.0  banana  False
2  test   8.0  orange   True
3   4.0   9.0    test  False
4   5.0  10.0   grape   test

Missing values after filling:

A    0
B    0
C    0
D    0
dtype: int64